#!/bin/bash

# Pomodoro durations
POMODORO_DURATION=25  # Pomodoro work duration in minutes
SHORT_BREAK=5         # Short break duration in minutes
LONG_BREAK=15         # Long break duration in minutes
POMODOROS_BEFORE_LONG_BREAK=4

TOMATO="🍅"
ICON_PATH="pomodoro.png"

# Function to display time countdown
countdown() {
    local duration=$1
    local message=$2
    local end=$((SECONDS + duration * 60))
    local paused=0
    local remaining=$((duration * 60))

    trap 'paused=1' SIGINT

    #Ctrl+c to pause
    printf "\nPress Ctrl+c to Pause...\n"

    while [ $remaining -gt 0 ]; do
        if [ $paused -eq 1 ]; then
            printf "\nPaused. Press 'p' to resume or 'q'/'ESC' to quit...\n"
            while true; do
                read -rsn1 key
                if [ "$key" == "p" ]; then
                    printf "Resuming...\n"
                    paused=0
                    break
                elif [[ "$key" == $'\e' || "$key" == "q" ]]; then
                    printf "\nExiting...\n"
                    exit 0
                fi
            done
        fi

        printf "\r$TOMATO - %s - %02d:%02d remaining" "$message" $((remaining / 60)) $((remaining % 60))
        read -rsn1 -t 1 key
        if [[ "$key" == $'\e' || "$key" == "q" ]]; then
            printf "\nExiting...\n"
            exit 0
        fi
        remaining=$((remaining - 1))
    done
    echo ""
}

# Function to send notifications
send_notification() {
    local title=$1
    local message=$2

    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS notification
        osascript -e "display notification \"$message\" with title \"$title\" subtitle \"\" sound name \"default\""
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux notification
        notify-send -i "$ICON_PATH" "$title" "$message"
    fi
}

pomodoro_count=0

while true; do
    # Pomodoro session
    send_notification "Pomodoro Timer" "Work session started"
    countdown $POMODORO_DURATION "Work session"
    ((pomodoro_count++))
    send_notification "Pomodoro Timer" "Pomodoro complete! Total: $TOMATO $pomodoro_count"
    echo "Pomodoro complete! Total: $TOMATO $pomodoro_count"
    
    if ((pomodoro_count % POMODOROS_BEFORE_LONG_BREAK == 0)); then
        # Long break
        send_notification "Pomodoro Timer" "Long break started"
        countdown $LONG_BREAK "Long break"
    else
        # Short break
        send_notification "Pomodoro Timer" "Short break started"
        countdown $SHORT_BREAK "Short break"
    fi
done
